/**************************************************************************************************************************************
 * Global Variables
 ***************************************************************************************************************************************/
const gsNewLineSpecialCharacter = "\u21B5";
const gsWhiteSpaceSpecialCharacter = "&nbsp;";
let giKeyUpEventCounter = 0;
const giCharacterBlockSizeMax = 50; /*Maximale Anzahl an Zeichen bis zum ersten 'Enter' Symbol*/
const giCharactersStartTop = 50;
const giCharactersStartleft = 50;
const giCharactersStartTransformY= -40;
const giCharacterDivWidth = 42; /*Gleicher Wert wie in style.css*/
let arNewElements = []; /* Hier werden die neuen Element zwischen gespeichert*/
const gsCurrentCharacterClass = "CurrentCharacter";
const gsCurrentCharacterId = "currentCharacter";
const gCharacters = [
  "a",
  "b",
  "c",
  "d",
  "e",
  "f",
  "g",
  "h",
  "i",
  "j",
  "k",
  "l",
  "m",
  "n",
  "o",
  "p",
  "q",
  "r",
  "s",
  "t",
  "u",
  "v",
  "w",
  "x",
  "y",
  "z",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "0",
  "ß",
  "!",
  "$",
  "%",
  "&",
  "/",
  "(",
  ")",
  "=",
  "?",
  ",",
  ".",
  "-",
  ";",
  ":",
  "_",
  "#",
  "'",
  "~",
  "|",
  "@",
  "{",
  "}",
  "[",
  "]",
  "\\",
  "\n",
  "\n", // double the propability of the new line character by adding another one
];

const gAltGrCharacters = ["{", "}", "[", "]", "\\", "@", "~", "|"];
